---
title: Papers
---

# 2025

- **Petak, C.**, Frati, L., Vroomans, R. M., Pespeni, M. H., and Cheney, N. (2025). The variability of evolvability: properties of dynamic fitness landscapes determine how phenotypic variability evolves. bioRxiv, 2025-07.
[Link to paper](https://www.biorxiv.org/content/10.1101/2025.07.02.662714v2)

- Weinreich, D. M., Sgouros, T., Raynes, Y., Burtsev, H., Chang, E., Rajakumar, S., Bravo, I.G. and **Petak, C.** (2025). The Population Genetics of Biological Noise. bioRxiv, 2025-01.

# 2024

- Frati, L., **Petak, C.**, & Cheney, N. (2024). Networks of Binary Necklaces Induced by Elementary Cellular Automata Rules. Artificial Life.


# 2023

- **Petak, C.**, Frati, L., Pespeni, M. H., & Cheney, N. (2023). Coping with seasons: evolutionary dynamics of gene networks in a changing environment. In Proceedings of the Companion Conference on Genetic and Evolutionary Computation (pp. 163-166).
[Link to paper](https://arxiv.org/abs/2307.01602)

- **Petak, C.**, Frati, L., Brennan, R. S., & Pespeni, M. H. (2023). Whole-genome sequencing reveals that regulatory and low pleiotropy variants underlie local adaptation to environmental variability in purple sea urchins. The American Naturalist, 202(4), 571-586.
[Link to paper](https://www.journals.uchicago.edu/doi/10.1086/726013)

# 2019

- Bunford, N., Csibra, B., **Peták, C.**, Ferdinandy, B., Miklósi, Á., & Gácsi, M. (2019). Associations among behavioral inhibition and owner-rated attention, hyperactivity/impulsivity, and personality in the domestic dog (Canis familiaris). Journal of comparative psychology, 133(2), 233.


